services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: '4gb'

volumes:
  postgres_data:
    driver: local
